import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/Header";
import Ramp from "../components/Ramp";

const Home: NextPage = () => {
  const myArray = ['Element 0', 'Element 1', 'Element 2', 'Element 3'];
  const myStr = 'MONDAY! MONDAY! MONDAY!';
  return (
    <>
      <Head>
        <title>Ramp ReVamp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="text-center min-h-screen">
        <section className="p-8">
          <p className="italic font-bold mb-2">Undefined value:</p>
          <Ramp />
        </section>
        <section className="p-8">
          <p className="italic font-bold mb-2">Array type:</p>
          <Ramp input={myArray} />
        </section>
        <section className="p-8">
          <p className="italic font-bold mb-2">Everything else:</p>
          <Ramp input={myStr} />
        </section>
      </main>
    </>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard: React.FC<TechnologyCardProps> = ({
  name,
  description,
  documentation,
}) => {
  return (
    <section className="flex flex-col justify-center rounded border-2 border-gray-500 p-6 shadow-xl duration-500 motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <Link
        className="m-auto mt-3 w-fit text-sm text-violet-500 underline decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </Link>
    </section>
  );
};
